options:
  log_level:
    description: |
      Configures the log level. 

      Acceptable values are: "info", "debug", "warning", "error" and "critical"
    default: "info"
    type: string
  base_dn:
    description: base DN
    default: "dc=glauth,dc=com"
    type: string
